name: envato
description: wem2017.github.io
version: 1.2.4+48
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.3
  firebase_core: ^1.6.0
  firebase_analytics: ^8.3.2
  firebase_messaging: ^10.0.7
  shared_preferences: ^2.0.7
  intl: ^0.17.0
  bloc: ^7.1.0
  flutter_bloc: ^7.2.0
  timeago: ^3.1.0
  webview_flutter: ^2.0.12
  dio: ^4.0.0
  device_info: ^2.0.2
  cached_network_image: ^3.1.0
  shimmer: ^2.0.0
  rxdart: ^0.27.2
  sqflite: ^2.0.0+4
  flutter_svprogresshud: ^0.0.7
  google_mobile_ads: ^0.13.4
  qr_code_scanner: ^0.5.2
  flutter_colorpicker: ^0.5.0
  flutter_app_badger:
    git:
      url: https://github.com/SuaMusica/flutter_app_badger.git
      ref: feature/androidV2

flutter:
  assets:
    - assets/images/
    - assets/locale/
    - assets/animation/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-LightItalic.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova-Black.otf
        - asset: assets/fonts/ProximaNova-Bold.otf
        - asset: assets/fonts/ProximaNova-Extrabld.otf
        - asset: assets/fonts/ProximaNova-Regular.otf
        - asset: assets/fonts/ProximaNovaT-Thin.otf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Black.ttf
        - asset: assets/fonts/Raleway-BlackItalic.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-BoldItalic.ttf
        - asset: assets/fonts/Raleway-ExtraBold.ttf
        - asset: assets/fonts/Raleway-ExtraBoldItalic.ttf
        - asset: assets/fonts/Raleway-ExtraLight.ttf
        - asset: assets/fonts/Raleway-ExtraLightItalic.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
        - asset: assets/fonts/Raleway-Light.ttf
        - asset: assets/fonts/Raleway-LightItalic.ttf
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-MediumItalic.ttf
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-SemiBold.ttf
        - asset: assets/fonts/Raleway-SemiBoldItalic.ttf
        - asset: assets/fonts/Raleway-Thin.ttf
        - asset: assets/fonts/Raleway-ThinItalic.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-BlackItalic.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-BoldItalic.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-LightItalic.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto-ThinItalic.ttf
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Black.ttf
        - asset: assets/fonts/Merriweather-BlackItalic.ttf
        - asset: assets/fonts/Merriweather-Bold.ttf
        - asset: assets/fonts/Merriweather-BoldItalic.ttf
        - asset: assets/fonts/Merriweather-Italic.ttf
        - asset: assets/fonts/Merriweather-Light.ttf
        - asset: assets/fonts/Merriweather-LightItalic.ttf
        - asset: assets/fonts/Merriweather-Regular.ttf
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4